- name: Set Hostname
  ansible.builtin.shell: set-hostname backend

- name: Verify NodeJS
  ansible.builtin.shell: type npm
  register: npm
  ignore_errors: yes

- name: Install NodeJS repo file
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  when: npm.rc != 0

- name: Installing NodeJS
  ansible.builtin.dnf:
    name: nodejs
  when: npm.rc != 0

- name: Copying backend.service file
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Adding Application user
  ansible.builtin.user:
    name: expense

- name: Calling app pre requisite
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq

- name: Install Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Restart Backend service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes

- name: Installing MySQL client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: Load Schema
  ansible.builtin.shell: mysql -h {{ lookup('aws_ssm', 'expense.backend.DB_HOST', region='us-east-1' ) }} -uroot -p{{ lookup('aws_ssm', 'expense.mysql.DB_PASS', region='us-east-1' ) }} < /app/schema/backend.sql