- name: Copy Elastic yum repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install Filebeat
  ansible.builtin.dnf:
    name: filebeat
    state: installed

- name: Copy filebeat config
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Start filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes